let productos = [
    ['Leche', 1, 'Producto bebible lacteo', 'https://statics-cuidateplus.marca.com/cms/styles/natural/azblob/lecheok_0.jpg.webp?itok=0XaoEZv0'],
    ['Computadora', 1, 'Dispositivo informático que es capaz de recibir, almacenar y procesar información de una forma útil.', 'https://www.tecnologia-informatica.com/wp-content/uploads/2018/08/caracteristicas-de-las-computadoras-1.jpeg'],
    ['Cafe', 1, 'Bebida que se obtiene a partir de los granos tostados y molidos de los frutos de la planta del café', 'https://www.caracteristicas.co/wp-content/uploads/2018/09/caf%C3%A9-e1578772027254.jpg'],
    ['Servilletas', 1, 'Pieza rectangular elaborada de tela para secar o limpiar manos o boca', 'https://diccionarioactual.com/wp-content/uploads/2016/05/servilleta.jpg'],
    ['Audifonos', 1, 'Aparato electrónico que se usa dentro o detrás de la oreja. Amplifica ciertos sonidos, y al hacerlos más fuertes se hace más fácil oírlos.', 'https://definicion.de/wp-content/uploads/2020/12/Auriculares-intraurales.jpg'],
    ['Termo', 1, 'Recipiente que se utiliza para mantener la temperatura de un fluido.', 'https://upload.wikimedia.org/wikipedia/commons/f/fc/Thermos.JPG'],
    ['Lentes', 1, 'Objeto colocado en los ojos, apoyado en la nariz, para ayudar a mejorar la vista.', 'https://espaciociencia.com//wp-content/uploads/tipos-de-lentes-instagram-ok-vision-lentes.jpg'],
    ['Telefono Celular', 1, 'Dispositivo informatico portatil capaz de realizar llamadas telefonicas y conectarse a la red.', 'https://m.media-amazon.com/images/I/61m1Dot5KCL._AC_SS450_.jpg'],
    ['Gorra', 1, 'Accesorio diseñado y creado para cubrir la cabeza y proteger los ojos de la luz natural (solar) y la luz artificial (eléctrica) mediante una visera y una pieza ajustable al cráneo, que puede incluir alas laterales.', 'https://tottoguatemala.vteximg.com.br/arquivos/ids/292306-292-292/AC60IND675-2210M-G03_1.jpg?v=637868088300500000'],
    ['Mochila', 1, 'Bolsa de lona provista de correas para ser cargada a la espalda , sirve para llevar provisiones o equipos en excursiones , expediciones , viajes , etc.', 'https://molvu.com/image/cache/catalog/Productos/Mochilas/MolvuU2/mochila-u2-azul-400x400.jpg']
]